AWSTemplateFormatVersion: '2010-09-09'
Description:  Stack to deploy a highly available web application. It launches multiple nested stacks for different tiers
Metadata:
  Authors:
    Description: Olivier Mbida (olivier.mbida@ai-uavsystems.com)
Parameters:
  AWSRegion:
    Description: AWS Region for stack creation
    Type: String
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    Default: us-east-1
  VpcAzs:
    Description: Availability Zones used in VPC.
    Type: CommaDelimitedList
  AzsMap:
    Description: Availability Zones Map. Must match available zones in VpcAZs parameter
    Type: String
  VpcCidr:
    Description: CIDR block for the VPC
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
  VpcTenancy:
    Description: The allowed tenancy of instances launched into the VPC
    Type: String
    AllowedValues:
      - default
      - dedicated
    Default: default
  EMailAddress:
    Description: Email address for SNS issue notification
    Type: String
    AllowedPattern: ^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
    ConstraintDescription: Enter a valid email address
  S3BucketName:
    Description: S3 bucket name for Vpc Gateway Endpoint
    Type: String
  SshAccessCidr:
    Description: The CIDR IP range that is permitted to SSH to bastion instance. Note
      - a value of 0.0.0.0/0 will allow access from ANY IP address.
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 0.0.0.0/0
  EnvironmentType: 
    Description: The environment type for web application
    Type: String
    Default: test
    AllowedValues: 
      - dev
      - test
      - prod
    ConstraintDescription: Must be a development (dev), test or production (prod) environment.
  EC2KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    NoEcho: true
    Description: Name of an EC2 KeyPair. Bastion and web auto scaling group instances will launch with this KeyPair.
  BastionInstanceType:
    Description: Bastion EC2 instance type.
    Type: String
    AllowedValues:
      - t1.micro
      - t2.micro
    ConstraintDescription: Must be a valid Amazon EC2 instance type free tier eligible.
    Default: t2.micro
  WebAppInstanceType:
    Description: WebApp Auto scaling Group instance type.
    Type: String
    AllowedValues:
      - t1.micro
      - t2.micro
      - t3.medium
    ConstraintDescription: Must be a valid Amazon EC2 instance type free tier eligible.
    Default: t2.micro
  WebAppAsgMax:
    Description: Specifies the maximum number of EC2 instances in the Web Autoscaling Group.
    Type: String
    AllowedPattern: ^((?!0$)[1-2]?[0-9]|20)$
    ConstraintDescription: Must be a number between 1 and 20.
    Default: "5"
  WebAppAsgMin:
    Description: Specifies the minimum number of EC2 instances in the Web Autoscaling Group.
    Type: String
    AllowedPattern: ^([0-0]?[0-9]|5)$
    ConstraintDescription: Must be a number between 0 and 5.
    Default: "2"
  PublicSubnet0Cidr:
    Description: CIDR block for Public subnet 0 located in Availability Zone 0
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.200.0/24
  PublicSubnet1Cidr:
    Description: CIDR block for Public subnet 1 located in Availability Zone 1
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.201.0/24
  PublicSubnet2Cidr:
    Description: CIDR block for Public subnet 2 located in Availability Zone 2
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.202.0/24
  PublicSubnet3Cidr:
    Description: CIDR block for Public subnet 3 located in Availability Zone 3
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.203.0/24
  PublicSubnet4Cidr:
    Description: CIDR block for Public subnet 4 located in Availability Zone 4
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.204.0/24
  PublicSubnet5Cidr:
    Description: CIDR block for Public subnet 5 located in Availability Zone 5
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.205.0/24
  PrivateSubnet0Cidr:
    Description: CIDR block for Private subnet 0 located in Availability Zone 0
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/22
  PrivateSubnet1Cidr:
    Description: CIDR block for Private subnet 1 located in Availability Zone 1
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.4.0/22
  PrivateSubnet2Cidr:
    Description: CIDR block for Private subnet 2 located in Availability Zone 2
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.8.0/22
  PrivateSubnet3Cidr:
    Description: CIDR block for Private subnet 3 located in Availability Zone 3
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.12.0/22
  PrivateSubnet4Cidr:
    Description: CIDR block for Private subnet 4 located in Availability Zone 4
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.16.0/22
  PrivateSubnet5Cidr:
    Description: CIDR block for Private subnet 5 located in Availability Zone 5
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.20.0/22
  UseCloudFront:
    Description: Choose if CloudFront Distribution is to serve the Web application content.
    Type: String
    AllowedValues:
      - true
      - false
    Default: true
  UseRoute53:
    Description: Choose if Route53 Distribution is to serve the Web application content.
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
  DomainName:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: '[ Optional ] The main domain name of the web application site (e.g. example.com).'
    Type: String
    Default: "example.com"
Conditions:
  CloudFrontAvailable:
    !Equals [ !Ref UseCloudFront, true ]
  Route53Available:
    !Equals [ !Ref UseRoute53, true ]

Resources:
  route53:
    Condition: Route53Available
    DependsOn: 
      - publicalb
      - webAppAsg 
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DnsEndpoint:
          !If [ CloudFrontAvailable, !GetAtt [ cloudfront, Outputs.DnsEndpoint ], !GetAtt [ publicalb, Outputs.PublicAlbDnsName ] ]
        DnsHostId:
          !If [ CloudFrontAvailable, 'Z2FDTNDATAQYW2', !GetAtt [ publicalb, Outputs.PublicAlbCanonicalHostedZoneId ] ]
        DomainName:
          !Ref DomainName
      TemplateURL: webApp_r53.yaml
  cloudfront:
    Condition: CloudFrontAvailable
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - publicalb
      - webAppAsg 
    Properties:
      Parameters:
        PublicAlbDnsName:
          !GetAtt [ publicalb, Outputs.PublicAlbDnsName ]
      TemplateURL: webApp_cdn.yaml
  # cloudwatch:
  #   DependsOn: 
  #     - newvpc
  #     - securitygroups
  #     - publicalb
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     Parameters:
  #       PublicAlbFullName:
  #         !GetAtt [ publicalb, Outputs.PublicAlbFullName ]     
  #     TemplateURL: webApp_dash.yaml
  publicalb:
    DependsOn: 
      - newvpc
      - securitygroups 
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Subnets:
          Fn::GetAtt:
          - newvpc
          - Outputs.PublicSubnets
        AlbSecurityGroup:
          Fn::GetAtt:
          - securitygroups
          - Outputs.PublicAlbSecurityGroup
        Vpc:
          Fn::GetAtt:
          - newvpc
          - Outputs.Vpc
      Tags:
      - Key: Name
        Value: webApp-Alb
      TemplateURL: webApp_Alb.yaml
  webAppAsg:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - newvpc
      - securitygroups
      - publicalb
    Properties:
      Parameters:
        AWSRegion:
          Ref: AWSRegion
        EnvironmentType:
          Ref: EnvironmentType
        EC2KeyName:
          Ref: EC2KeyName
        WebAppSecurityGroup:
          Fn::GetAtt:
          - securitygroups
          - Outputs.WebAppSecurityGroup
        WebAppInstanceType:
          Ref: WebAppInstanceType
        WebAppAsgMax:
          Ref: WebAppAsgMax
        WebAppAsgMin:
          Ref: WebAppAsgMin
        ApplicationTargetGroup:
          Fn::GetAtt:
          - publicalb
          - Outputs.PublicAlbTargetGroupArn
        PublicAlbHostname:
          Fn::GetAtt:
          - publicalb
          - Outputs.PublicAlbHostname
        Subnets:
          Fn::GetAtt:
          - newvpc
          - Outputs.PrivateSubnets
        AzsMap: 
          Ref: AzsMap
        S3BucketName:
          Ref: S3BucketName
      Tags:
      - Key: Name
        Value: webApp-Asg
      TemplateURL: webApp_Asg.yaml
  bastion:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - newvpc
      - securitygroups
    Properties:
      Parameters:
        AWSRegion:
          Ref: AWSRegion
        EMailAddress: 
          Ref: EMailAddress
        EnvironmentType:
          Ref: EnvironmentType
        EC2KeyName:
          Ref: EC2KeyName
        BastionSecurityGroup:
          Fn::GetAtt:
          - securitygroups
          - Outputs.BastionSecurityGroup
        BastionInstanceType:
          Ref: BastionInstanceType
        Subnets:
          Fn::GetAtt:
          - newvpc
          - Outputs.PublicSubnets
        AzsMap: 
          Ref: AzsMap
      Tags:
      - Key: Name
        Value: network-bastion
      TemplateURL: network_bastion.yaml
  securitygroups:
    Type: AWS::CloudFormation::Stack
    DependsOn: newvpc
    Properties:
      Parameters:
        SshAccessCidr:
          Ref: SshAccessCidr
        Vpc:
          Fn::GetAtt:
          - newvpc
          - Outputs.Vpc
        VpcCidr:
          Fn::GetAtt:
          - newvpc
          - Outputs.VpcCidr
      Tags:
      - Key: Name
        Value: network-securitygroups
      TemplateURL: network_sgs.yaml
  newvpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AWSRegion:
          Ref: AWSRegion
        S3BucketName:
          Ref: S3BucketName
        VpcCidr:
          Ref: VpcCidr
        SshAccessCidr:
          Ref: SshAccessCidr
        VpcTenancy:
          Ref: VpcTenancy
        VpcAzs:
          Fn::Join:
          - ','
          - - Fn::Select:
              - 0
              - Ref: VpcAzs
            - Fn::Select:
              - 1
              - Ref: VpcAzs
            - Fn::Select:
              - 2
              - Ref: VpcAzs
            - Fn::Select:
              - 3
              - Ref: VpcAzs
            - Fn::Select:
              - 4
              - Ref: VpcAzs
            - Fn::Select:
              - 5
              - Ref: VpcAzs
        AzsMap:
          Ref: AzsMap
        PublicSubnetCidrBlocks:
          Fn::Join:
          - ','
          - - Ref: PublicSubnet0Cidr
            - Ref: PublicSubnet1Cidr
            - Ref: PublicSubnet2Cidr
            - Ref: PublicSubnet3Cidr
            - Ref: PublicSubnet4Cidr
            - Ref: PublicSubnet5Cidr
        PrivateSubnetCidrBlocks:
          Fn::Join:
          - ','
          - - Ref: PrivateSubnet0Cidr
            - Ref: PrivateSubnet1Cidr
            - Ref: PrivateSubnet2Cidr
            - Ref: PrivateSubnet3Cidr
            - Ref: PrivateSubnet4Cidr
            - Ref: PrivateSubnet5Cidr
      Tags:
      - Key: Name
        Value: network-vpc
      TemplateURL: network_vpc.yaml